version: '3.8'

services:
  auth_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./configs:/configs
    env_file:
      - ./.env
    networks:
      - monitoring
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: pushpost_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pushword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - monitoring
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
  monitoring:
volumes:
  pgdata:
